config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, controller: 'users', only: %i[edit create show update] do
    get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    resource :password,
             controller: 'clearance/passwords',
             only: %i[edit update]
  end

  get '/sign-in' => 'sessions#new', as: 'sign_in'
  delete '/sign-out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign-up' => 'clearance/users#new', as: 'sign_up'
  get 'successful-signup' => 'users#successful_signup', as: 'successful_signup'
  root to: 'home#index'

  resources :units, except: %i[index show] do
    get '/sign-up' => 'clearance/users#new', as: 'sign_up'
    resources :users, only: [:destroy]
    resources :activities do
      post 'copy' => 'activities#copy', as: 'copy'
      resources :questions do
        resources :answers, only: %i[new create destroy]
      end
      post '/archive-activity' => 'activities#archive_activity', as: 'archive_activity'
    end
    resources :unit_votes, only: %i[index create destroy]
  end

  resources :activities, only: [:show]

  get 'about' => 'home#about', as: 'about'
  get 'faqs' => 'home#faqs', as: 'faqs'
  get 'resources' => 'home#resources', as: 'activity_resources'
  get '/sitemap' => 'sitemap#sitemap', as: 'sitemap'
  get 'fundraising-activity-ideas' => 'activities#ideas_for_fundraising_activities', as: 'fundraising_activity_ideas'
  get 'troop-activity-ideas' => 'activities#ideas_for_troop_activities', as: 'troop_activity_ideas'
  get 'covid-safe-troop-activity-ideas' => 'activities#ideas_for_covid_safe_troop_activities', as: 'covid_safe_troop_activity_ideas'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :activity
  has_many :answers, dependent: :destroy

  validates :content, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :activity

  def index
    @questions = @activity.questions.include(:answers)
  end

  def show; end

  def edit; end

  def new
    @question = @activity.questions.new
  end

  def create
    @question = @activity.questions.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to unit_activity_path(@unit, @activity), notice: 'Your question has been posted.'
    else
      render :new
    end
  end

  def update; end

  def destroy
    question = @activity.questions.find(params[:id])
    question.destroy if @activity.author == current_user || question.user == current_user
    redirect_to unit_activity_path(@unit, @activity)
  end

  private

  def activity
    @activity = Activity.find(params[:activity_id])
  end

  def question_params
    params.require(:question).permit(:content)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= form_for [@unit, @activity, @question] do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :question, 'Question or comment on this activity?'
    = f.text_field :content, class: 'form-control', placeholder: 'Enter your question or comment'


  .action
    = f.submit "Ask your question or comment", class: 'btn btn-primary'

app/views/questions/_question.html.haml
.question
  = question.content
  - if @activity.author == current_user || question.user == current_user || (current_user.admin_or_owner? && current_user.unit == @activity.unit)
    = link_to unit_activity_question_path(@unit, @activity, question), method: :delete, id: "question-#{question.id}-destroy-link" do
      = fa_icon "trash-alt"
.question-author= question.user.email

- question.answers.each do |answer|
  .answer
    = answer.content
    - if @activity.author == current_user || answer.user == current_user || (current_user.admin_or_owner? && current_user.unit == @activity.unit)
      = link_to unit_activity_question_answer_path(@unit, @activity, question, answer), method: :delete, id: "answer-#{answer.id}-destroy-link" do
        = fa_icon "trash-alt"
  .answer-author= answer.user.email

- if signed_in? && @unit == current_user.unit
  = link_to "Add answer/comment", new_unit_activity_question_answer_path(@unit, @activity, question), class: 'answer-link', id: "question-#{question.id}-add-answer-link"

app/views/questions/edit.html.haml
%h1 Questions#edit
%p Find me in app/views/questions/edit.html.haml

app/views/questions/index.html.haml
%h1 Questions#index
%p Find me in app/views/questions/index.html.haml

app/views/questions/new.html.haml
.row
  .col-md-12
    %h2= link_to @activity.name, unit_activity_path(@unit, @activity)

.row
  .col-md-12
    %h1 Ask a Question


%br

.row
  .col-md-8
    = render 'form'


%br
= link_to "< " + @activity.name, unit_activity_path(@unit, @activity)

app/views/questions/show.html.haml
%h1 Questions#show
%p Find me in app/views/questions/show.html.haml