config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, controller: 'users', only: %i[edit create show update] do
    get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    resource :password,
             controller: 'clearance/passwords',
             only: %i[edit update]
  end

  get '/sign-in' => 'sessions#new', as: 'sign_in'
  delete '/sign-out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign-up' => 'clearance/users#new', as: 'sign_up'
  get 'successful-signup' => 'users#successful_signup', as: 'successful_signup'
  root to: 'home#index'

  resources :units, except: %i[index show] do
    get '/sign-up' => 'clearance/users#new', as: 'sign_up'
    resources :users, only: [:destroy]
    resources :activities do
      post 'copy' => 'activities#copy', as: 'copy'
      resources :questions do
        resources :answers, only: %i[new create destroy]
      end
      post '/archive-activity' => 'activities#archive_activity', as: 'archive_activity'
    end
    resources :unit_votes, only: %i[index create destroy]
  end

  resources :activities, only: [:show]

  get 'about' => 'home#about', as: 'about'
  get 'faqs' => 'home#faqs', as: 'faqs'
  get 'resources' => 'home#resources', as: 'activity_resources'
  get '/sitemap' => 'sitemap#sitemap', as: 'sitemap'
  get 'fundraising-activity-ideas' => 'activities#ideas_for_fundraising_activities', as: 'fundraising_activity_ideas'
  get 'troop-activity-ideas' => 'activities#ideas_for_troop_activities', as: 'troop_activity_ideas'
  get 'covid-safe-troop-activity-ideas' => 'activities#ideas_for_covid_safe_troop_activities', as: 'covid_safe_troop_activity_ideas'
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } # this allows bad emails such as "test@examplecom"

  belongs_to :unit, optional: true
  has_many :unit_votes, dependent: :destroy
  has_many :activities, foreign_key: 'author_id', dependent: :nullify
  has_many :questions, dependent: :nullify
  has_many :answers, dependent: :nullify
  has_many :logs, dependent: :destroy

  scope :owner, -> { where(is_owner: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :app_admin, -> { where(is_app_admin: true) }
  scope :active, -> { where('last_sign_in_at > ?', Time.now - 7.days) }

  before_save :clear_unit_votes!, if: proc { |u| u.unit_id_changed? }
  before_save :remove_admin!, if: proc { |u| u.unit_id_changed? && u.persisted? }

  def initialize(args)
    super(args)
    self.token = SecureRandom.hex unless token.present?
  end

  def unit_votes_available
    unit.votes_allowed - unit_votes.joins(:activity).where("activities.unit_id = ?", unit_id).count
  end

  def example_votes_available
    Unit.example.first.votes_allowed - example_unit_votes_count
  end

  def name_email
    result = ''
    result = "#{last_name} #{result}" if last_name.present? && first_name.present?
    result = "#{first_name} #{result}" if first_name.present?
    if result.present?
      "#{result}(#{email})"
    else
      email
    end
  end

  def admin?
    is_admin
  end

  def owner?
    is_owner
  end

  def admin_or_owner?
    admin? || owner?
  end

  def clear_unit_votes!
    unit_votes.destroy_all
  end

  def remove_admin!
    self.is_admin = false
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :require_login, except: %i[unsubscribe new create destroy]
  before_action :set_user, only: %i[edit update destroy]
  before_action :require_admin_owner, only: %i[edit update destroy]
  before_action :set_title, only: [:edit]

  def edit; end

  def update
    new_params = user_params.reject! { |_k, v| v.blank? }
    if @user.update(new_params)
      redirect_to unit_activities_path(@user.unit), notice: 'Your account has been updated'
    else
      render :edit
    end
  end

  def destroy
    @user.update(unit_id: nil)
    redirect_to edit_unit_path(@unit)
  end

  def unsubscribe
    @user = User.find(params[:user_id])
    @user.update(is_subscribed: false)
  end

  def url_after_create
    successful_signup_path(signup: 'success')
  end

  def successful_signup
    @title = 'You are signed up - Scout Activity'
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_title
    @title = 'Profile - Scout Activity'
  end

  def user_params
    params.require(:user).permit(:email, :password, :unit_id, :is_subscribed, :is_admin, :first_name, :last_name)
  end

  def require_admin_owner
    redirect_to root_path unless current_user == @user || (current_user.admin_or_owner? && current_user.unit == @user.unit)
  end
end

app/views/users/_form.html.haml
.form-group
  = form.label :email
  = form.email_field :email, class: 'form-control'


.form-group
  = form.label :password
  = form.password_field :password, class: 'form-control'

- if @unit
  = form.hidden_field :unit_id, value: @unit.id
- else
  .form-group

    = form.label :unit
    
    = form.collection_select :unit_id, Unit.all, :id, :name, {include_blank: true }, class: 'form-control', id: 'unit-select', disabled: @user && @user.persisted? && @user.unit.present? && @user.is_owner?
    - unless current_user
      %small.text-muted Select your Unit, or leave blank if your Unit has not been added yet. You'll do that next.

  - if @user.persisted? && @user.unit.nil?
    %p= link_to "Add a Unit", new_unit_path

- if @user.unit && !@user.owner? && current_user.admin_or_owner?
  .form-group.form-check-inline
    = form.check_box :is_admin, class: 'form-check-input'
    = form.label :admin, class: 'form-check-label'

- if @user.owner?
  .form-group.form-check-inline
    = form.check_box :is_owner, class: 'form-check-input', disabled: true
    = form.label :owner, class: 'form-check-label'

- if current_user && current_user.persisted?
  %br
  .form-group
    = form.label :first_name
    = form.text_field :first_name, class: 'form-control'

  .form-group
    = form.label :last_name
    = form.text_field :last_name, class: 'form-control'

  .form-check.form-check-inline
    = form.check_box :is_subscribed, class: 'form-check-input'
    = form.label :subscribed_to_emails, class: 'form-check-label'


%br

app/views/users/edit.html.haml
.row
  .col-md-3
  .col-md-6
    %h1.mb-5= @user.email

    = form_for @user do |form|
      - if @user.errors.any?
        #error_explanation
          .message= "Ouch! Some bad stuff stopped me from creating your account:"
          %ul
            - @user.errors.full_messages.each do |message|
              %li= message
      = render partial: '/users/form', object: form

      %br
      .submit-field
        = form.submit "Update", class: 'btn btn-primary'

app/views/users/new.html.haml
.row
  .col-md-12
    %h1 
      - if @unit
        Sign up to vote for
        = succeed("'s") do
          = @unit.name
        activities
      - else
        = t(".title")

.row
  .col-md-3
  .col-md-6
    #clearance.sign-up
      %p.mb-5.text-muted.text-center
        - if @unit
          Sign up to vote, or add an activity
        - else
          Sign up to vote, add a unit, or add an activity

      = form_for @user do |form|
        - if @user.errors.any?
          #error_explanation
            .message= "Ouch! Some bad stuff stopped me from creating your account:"
            %ul
              - @user.errors.full_messages.each do |message|
                %li= message
        = render partial: '/users/form', object: form

        .submit-field
          = form.submit class: 'btn btn-primary'

        .other-links
          Already signed up?
          = link_to t(".sign_in"), sign_in_path

app/views/users/successful_signup.html.haml
.row
  .col-md-3
  .col-md-6
    %h1.text-center
      = fa_icon "check"
    - if current_user.unit
      %h2.text-center
        You're signed up with
        = succeed(".") do
          = current_user.unit.name


        %h4.text-center.mt-4
          You can now
          = link_to "vote", unit_activities_path(current_user.unit)
          or
          = link_to "add an activity.", new_unit_activity_path(current_user.unit)
          
    - else
      %h2.text-center You're signed up.
      %h4.text-center.mt-4
        The next step is to
        = link_to "create a unit", new_unit_path
        or,
        = link_to "select an existing unit.", edit_user_path(current_user)

      %br
      %hr
      %h5.text-center.mb-3 Existing Troops
      - Unit.all.each do |t|
        .text-center= t.name

app/views/users/unsubscribe.html.haml
.row
  .col-md-12
    %h3.mb-3 Unsubscribed
    %p
      = succeed(",") do
        = @user.email
      you are unsubscribed from our emails.
    %p
      You can resubscribe from within
      = succeed(".") do
        = link_to "your account", edit_user_path(@user)