config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, controller: 'users', only: %i[edit create show update] do
    get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    resource :password,
             controller: 'clearance/passwords',
             only: %i[edit update]
  end

  get '/sign-in' => 'sessions#new', as: 'sign_in'
  delete '/sign-out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign-up' => 'clearance/users#new', as: 'sign_up'
  get 'successful-signup' => 'users#successful_signup', as: 'successful_signup'
  root to: 'home#index'

  resources :units, except: %i[index show] do
    get '/sign-up' => 'clearance/users#new', as: 'sign_up'
    resources :users, only: [:destroy]
    resources :activities do
      post 'copy' => 'activities#copy', as: 'copy'
      resources :questions do
        resources :answers, only: %i[new create destroy]
      end
      post '/archive-activity' => 'activities#archive_activity', as: 'archive_activity'
    end
    resources :unit_votes, only: %i[index create destroy]
  end

  resources :activities, only: [:show]

  get 'about' => 'home#about', as: 'about'
  get 'faqs' => 'home#faqs', as: 'faqs'
  get 'resources' => 'home#resources', as: 'activity_resources'
  get '/sitemap' => 'sitemap#sitemap', as: 'sitemap'
  get 'fundraising-activity-ideas' => 'activities#ideas_for_fundraising_activities', as: 'fundraising_activity_ideas'
  get 'troop-activity-ideas' => 'activities#ideas_for_troop_activities', as: 'troop_activity_ideas'
  get 'covid-safe-troop-activity-ideas' => 'activities#ideas_for_covid_safe_troop_activities', as: 'covid_safe_troop_activity_ideas'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @units = Unit.non_example.order(visit_event_count: :desc)
    @example_unit = Unit.example.first
    return unless signed_in? && current_user.unit.nil?

    flash[:alert] = "To vote, select a Unit in your <a href='/users/#{current_user.id}/edit'>Profile</a> settings."
  end

  def about
    @title = 'About - Scout Activity'
    @description = 'Scout Units need a constant source of good ideas for activities. Scout Activity can help in sourcing ideas from Scouts, parents, and the wider community and then allow for Scouts to vote on their favorites.'
  end

  def resources
    @title = 'Helpful Scout activity resources - Scout Activity'
    @description = 'A list of curated resources for sourcing Scout activities.'
  end

  def faqs
    @title = 'Frequently asked questions - Scout Activity'
    @description = 'Frequently asked questions about how to best use ScoutActivity.com'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
#info
  .row
    .col-md-12
      %h1 About

  .row
    .col-md-2
    .col-md-8
      %p Scout Activity helps in taking the ideas of Scouts, leaders, and parents on fun activities and to poll for the the popularity of the ideas. 
      .text-center
        %p= button_to "Get started!", root_path, method: :get, class: 'btn btn-primary'

  .row.mt-4
    .col-md-2
    .col-md-8
      %p
        %span.strong Why did I build ScoutActivity?
        I've been involved with Scouting for a long time, as an Eagle, Cubmaster, Committee Chair, and probably more roles. Scouting is by all efforts 'Scout led', but the reality is, they need good ideas to work with. Often these are activities reused over many years, with few new activities. So I thought, how can I create a way for parents to offer up ideas online (COVID is keeping us virtual) based on their own skillsets, that can be put in front of Scouts to read about and vote on.


  .row
    .col-md-2
    .col-md-8
      %p 
        %strong Free to use.
        ScoutActivity is free to use for Scout units. I'm covering the costs. At some point, I may add a
        %span.badge.badge-info donate
        button to help defray the cost of hosting. 


  .row
    .col-md-2
    .col-md-8
      %p.questions
        %span.strong Questions or feedback?
        Join our
        = link_to "Facebook Group", "https://www.facebook.com/groups/scoutactivity"
        or email me directly at
        = succeed(".") do
          = mail_to "carson.cole@gmail.com"

  .row
    .col-md-2
    .col-md-8
      %p
        ScoutActivity is a Ruby on Rails application that is open-sourced
        = link_to "here,", "https://github.com/carsoncole/scout_activity"
        so anyone can host and change it at will. Attribution is requested.

app/views/home/example_unit.html.haml
.row
  .col-md-3
  .col-md-6
    %h1 Example Unit

    %p Here is a unit with example activities:

    - if @example_unit
      = link_to @example_unit.name, unit_activities_path(@example_unit)

app/views/home/faqs.html.haml
.row
  .col-md-2
  .col-md-8
    #faqs
      %h1 ScoutActivity Frequently Asked Questions (FAQs)

      .faq
        %h2.question Does voting require registering?
        %p.answer Yes. A person must register AND they must select the correct Unit, as they can only vote for the Unit's activities that they selected. 

      .faq
        %h2.question How many votes does each User get?
        %p.answer The default number of votes is 20, but this can be changed by the adminstrator of the Unit.

      .faq
        %h2.question Can I delete or archive an activity?
        %p.answer Yes. Deleting or archiving can be done by the author of the activity or Administrator of the Unit and will remove the activity from voting and also return all votes.

      .faq
        %h2.question Can I reset the votes?
        %p.answer
          To remove votes, the Administrator of the Unit should set the votes allowed
          to `0`, which will remove all votes (the system will remove any user excess votes as you reduce the number). Once the votes have been removed, the votes allowed can be set to any number.

      .faq
        %h2.question Can I hide an activity?
        %p.answer
          Yes. If you are the author of the activity or a Unit admin, you can archive an activity, which will remove it from view, and return any of its votes. Unarchiving the activity will return it to the main activities list and it can be voted on.

      .faq
        %h2.question Can I copy an activity?
        %p.answer
          Yes. You must be a Unit administrator (you created the Unit). View any activity and click the copy link, which will result in the activity being copied. Images will be copied. Questions and answers will not be copied.
          %br
          .text-center= image_tag "activity-action-links.jp2", class: 'img-fluid rounded shadow-sm p-3 mb-5'

      .faq
        %h2.question Can I give admin rights to other users?
        %p.answer
          Yes. Owners of Units (whomever created the Unit), can assign users as Admins in Unit settings.

app/views/home/index.html.haml
#home
  .d-none.d-sm-block
    .row
      .col-md-3
      .col-md-6.text-center
        = image_tag "scout-activity-vertical.png", class: 'logo img-fluid', id: 'root-page-logo', width: 250

    .row
      .col-md-2
      .col-md-8
        %h2.text-muted.text-center Scouting leader tool for new activity ideas.

  - if @example_unit
    .row
      .col-md-12.text-center
        = link_to 'View All Activity Ideas', unit_activities_path(@example_unit), class: 'btn btn-warning btn-lg'

  %br

  %aside#troop-selection
    .row
      .col-md-12.text-center
        %h1.choice Select a Troop

    .row
      .col-md-1
      .col-md-10.mb-3.text-center
        - @units.each do |unit|
          - if signed_in? && current_user.unit == unit
            = link_to unit.name, unit_activities_path(unit), class: 'btn btn-outline-primary troop'
          - else
            = link_to unit.name, unit_activities_path(unit), class: 'btn btn-primary troop'

    .row
      .col-md-2
      .col-md-8.justify-content-center
        - if signed_in?
          - if current_user.unit.nil?
            %h2.choice Or, if your Unit is not listed
            .text-center= button_to "Add your Unit", new_unit_path, method: :get, class: 'btn btn-warning btn-lg'
        - else 
          %h2.choice Or, if your Unit is not listed
          .text-center= button_to "Add your Own Unit Ideas", sign_up_path, method: :get, class: 'btn btn-warning btn-lg'

  = render 'features'

app/views/home/info.html.haml
#info
  .row
    .col-md-12
      %h1 Info

  .row
    .col-md-2
    .col-md-8
      %p Scout Activity helps in taking the ideas of Scouts, leaders, and parents on fun activities and to poll for the the popularity of the ideas. 
      .text-center
        %p= button_to "Get started!", root_path, method: :get, class: 'btn btn-primary'

  .row.mt-4
    .col-md-2
    .col-md-8
      %p
        %span.strong Why did I build ScoutActivity?
        I've been involved with Scouting for a long time, as an Eagle, Cubmaster, Committee Chair, and probably more roles. Scouting is by all efforts 'Scout led', but the reality is, they need good ideas to work with. Often these are activities reused over many years, with few new activities. So I thought, how can I create a way for parents to offer up ideas online (COVID is keeping us virtual) based on their own skillsets, that can be put in front of Scouts to read about and vote on.

  .row
    .col-md-2
    .col-md-8
      %p.questions
        %span.strong Questions or feedback?
        = mail_to "carson.cole@gmail.com"

  .row
    .col-md-2
    .col-md-8
      %br
      %p 
        ScoutActivity code is open sourced
        = link_to "here.", "https://github.com/carsoncole/scout_activity"

app/views/home/resources.html.haml
#resources
  .row
    .col-md-12
      %h1 Activity Resources

  .row
    .col-md-2
    .col-md-8

      %ul
        %li
          = link_to "BSA/Annual Planning Conference", "https://troopleader.scouting.org/annual-planning-conference/", target: '_blank'
          Long-term planning happens at the Annual Planning Conference, a Scout-led, Scoutmaster-guided conference to plan out Unit activities.
        %li
          = link_to "BSA/Monthly Planning and the PLC", "https://troopleader.scouting.org/patrol-leaders-council/", target: '_blank'
          Good description of the Patrol Leaders' Council (PLC), its purpose, and how it functions.
        %li
          = link_to "BSA/Program Features", "https://troopleader.scouting.org/program-features", target: '_blank'
          48 themed modules to help make program planning easier for troop leaders.
        %li
          = link_to "100 Ideas for Troop Meetings", "http://www.thedump.scoutscan.com/100ideastroop.pdf", target: '_blank'
          A collection of classic Troop meeting ideas that may inspire you.
        %li
          = link_to "ScoutShare.org", "http://scoutshare.org", target: '_blank'
          A site to find resources and ideas for your Scouting Unit.
        %li
          = link_to "Boy Scout Trail", "https://boyscouttrail.com", target: '_blank'
          A good general site for everything Scouting, from activities and jokes, to skits and songs.
        %li
          = link_to "101 Great Scout Service Project Ideas", "https://blog.scoutingmagazine.org/2015/10/09/101-great-scout-service-project-ideas/", target: '_blank'
          A comprehensive list of ideas for service projects.
        %li
          = link_to "Cub Scout Ideas", "https://cubscoutideas.com", target: '_blank'
          Cub Scout-focused information and activities site.


      %p.mt-5
        %strong Have a resource?
        Send it to me!
        =mail_to "carson.cole@gmail.com"

app/views/home/top_activities.html.haml
#activities
  .row
    .col-md-8
      %h1 Top Scout Troop Activities

      %nav.nav#activity-filter
        = link_to top_activities_path(filter: 'is_hiking'), class: "nav-link #{params[:filter]=='is_hiking' ? 'active':nil}" do
          = fa_icon "hiking"
        = link_to top_activities_path(filter: 'is_swimming'), class: "nav-link #{params[:filter]=='is_swimming' ? 'active':nil}" do
          = fa_icon "swimmer"
        = link_to top_activities_path(filter: 'is_biking'), class: "nav-link #{params[:filter]=='is_biking' ? 'active':nil}" do
          = fa_icon "biking"
        = link_to top_activities_path(filter: 'is_plane'), class: "nav-link #{params[:filter]=='is_plane' ? 'active':nil}" do
          = fa_icon "plane"
        = link_to top_activities_path(filter: 'is_cooking'), class: "nav-link #{params[:filter]=='is_cooking' ? 'active':nil}" do
          = fa_icon "utensils"
        = link_to top_activities_path(filter: 'is_merit_badge'), class: "nav-link #{params[:filter]=='is_merit_badge' ? 'active':nil}" do
          = image_tag "merit-badge.svg", width: '26px'
        = link_to top_activities_path(filter: 'is_camping'), class: "nav-link #{params[:filter]=='is_camping' ? 'active':nil}" do
          = fa_icon "campground"
        = link_to top_activities_path(filter: 'is_virtual'), class: "nav-link #{params[:filter]=='is_virtual' ? 'active':nil}" do
          = fa_icon "video"
        = link_to top_activities_path(filter: 'is_fundraising'), class: "nav-link #{params[:filter]=='is_fundraising' ? 'active':nil}" do
          = fa_icon "dollar-sign"
        = link_to top_activities_path(filter: 'is_game'), class: "nav-link #{params[:filter]=='is_game' ? 'active':nil}" do
          = fa_icon "trophy"
        = link_to top_activities_path(filter: 'is_boating'), class: "nav-link #{params[:filter]=='is_boating' ? 'active':nil}" do
          = fa_icon "anchor"
        = link_to top_activities_path(filter: 'is_community_service'), class: "nav-link #{params[:filter]=='is_community_service' ? 'active':nil}" do
          = fa_icon "store"
        = link_to top_activities_path(filter: 'is_international'), class: "nav-link #{params[:filter]=='is_international' ? 'active':nil}" do
          = image_tag "world-crest.png", width: '26px'
        = link_to top_activities_path(filter: 'is_high_adventure'), class: "nav-link #{params[:filter]=='is_high_adventure' ? 'active':nil}" do
          = fa_icon "mountain"
        = link_to "clear", top_activities_path, class: 'nav-link'

      %ul.activities.list-group
        = render @activities