config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, controller: 'users', only: %i[edit create show update] do
    get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    resource :password,
             controller: 'clearance/passwords',
             only: %i[edit update]
  end

  get '/sign-in' => 'sessions#new', as: 'sign_in'
  delete '/sign-out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign-up' => 'clearance/users#new', as: 'sign_up'
  get 'successful-signup' => 'users#successful_signup', as: 'successful_signup'
  root to: 'home#index'

  resources :units, except: %i[index show] do
    get '/sign-up' => 'clearance/users#new', as: 'sign_up'
    resources :users, only: [:destroy]
    resources :activities do
      post 'copy' => 'activities#copy', as: 'copy'
      resources :questions do
        resources :answers, only: %i[new create destroy]
      end
      post '/archive-activity' => 'activities#archive_activity', as: 'archive_activity'
    end
    resources :unit_votes, only: %i[index create destroy]
  end

  resources :activities, only: [:show]

  get 'about' => 'home#about', as: 'about'
  get 'faqs' => 'home#faqs', as: 'faqs'
  get 'resources' => 'home#resources', as: 'activity_resources'
  get '/sitemap' => 'sitemap#sitemap', as: 'sitemap'
  get 'fundraising-activity-ideas' => 'activities#ideas_for_fundraising_activities', as: 'fundraising_activity_ideas'
  get 'troop-activity-ideas' => 'activities#ideas_for_troop_activities', as: 'troop_activity_ideas'
  get 'covid-safe-troop-activity-ideas' => 'activities#ideas_for_covid_safe_troop_activities', as: 'covid_safe_troop_activity_ideas'
end

app/models/activity.rb
# TODO: Add icon for community service
class Activity < ApplicationRecord
  belongs_to :unit, touch: true
  belongs_to :author, optional: true, class_name: 'User'
  has_many :unit_votes, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many_attached :images

  scope :high_adventure, -> { where(is_high_adventure: true) }
  scope :non_high_adventure, -> { where(is_high_adventure: false) }
  scope :votable, -> { where(is_archived: false) }
  scope :archived, -> { where(is_archived: true) }
  scope :troop, -> { where(is_troop: true) }
  scope :pack, -> { where(is_pack: true) }
  scope :covid_safe, -> { where(is_covid_safe: true) }
  scope :fundraising, -> { where(is_fundraising: true) }

  validates :name, presence: true
  validates :name, length: { maximum: 75 }
  validates :summary_new, presence: true

  has_rich_text :summary
  has_rich_text :description
  has_rich_text :itinerary

  before_save :remove_votes_if_archived!, if: proc { |a| a.is_archived_changed? && a.is_archived? }
  after_save :update_covid_safe_count!, if: proc { |a| a.is_covid_safe_previously_changed? }
  after_save :update_troop_count!, if: proc { |a| a.is_troop_previously_changed? }
  after_save :update_fundraising_count!, if: proc { |a| a.is_fundraising_previously_changed? }

  def types
    result = []
    result << 'swimming' if is_swimming
    result << 'hiking' if is_hiking
    result << 'camping' if is_camping
    result << 'biking' if is_biking
    result << 'cooking' if is_cooking
    result
  end

  def categories
    result = []
    result << 'community service' if is_community_service
    result << 'international' if is_international
    result << 'merit badge opportunities' if is_merit_badge
    result << 'High Adventure' if is_high_adventure
    result << 'fundraising' if is_fundraising
    result << 'virtual' if is_virtual
    result
  end

  def activity_icons?
    if is_swimming || is_hiking || is_plane || is_camping || is_community_service || is_biking || is_cooking || is_virtual || is_international || is_merit_badge || is_high_adventure || is_fundraising || is_game
      true
    else
      false
    end
  end

  def self.duplicate(activity)
    new_activity = activity.dup
    new_activity.is_author_volunteering = false
    new_activity.author_id = false
    new_activity.unit_id = nil
    new_activity.unit_votes_count = 0
    new_activity.description = activity.description.dup
    new_activity.itinerary = activity.itinerary.dup
    new_activity
  end

  private

  def remove_votes_if_archived!
    unit_votes.destroy_all
  end

  def update_covid_safe_count!
    return unless unit.is_example?

    unit.update(covid_safe_count: unit.activities.covid_safe.count)
  end

  def update_fundraising_count!
    return unless unit.is_example?

    unit.update(fundraising_count: unit.activities.fundraising.count)
  end

  def update_troop_count!
    return unless unit.is_example?

    unit.update(troop_count: unit.activities.count)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  include ActivitiesHelper

  before_action :set_activity, only: %i[show edit update destroy]
  before_action :require_login, only: %i[create update destroy copy]
  before_action :require_unit_user, except: %i[index show copy ideas_for_troop_activities ideas_for_covid_safe_troop_activities ideas_for_fundraising_activities]
  before_action :require_author_admin_owner, only: %i[edit update destroy]
  before_action :set_title, except: %i[ideas_for_troop_activities ideas_for_covid_safe_troop_activities ideas_for_fundraising_activities]

  def index
    @activities = @unit.activities.votable.order(unit_votes_count: :desc)
    @high_adventure_activities = []
    if signed_in? && current_user.admin_or_owner? && current_user.unit == @unit
      @archived_activities = @unit.activities.archived if current_user.admin_or_owner? && current_user.unit == @unit
    elsif signed_in? && current_user.activities.where(unit_id: @unit.id).archived.any?
      @archived_activities = current_user.activities.where(unit_id: @unit.id).archived
    end
    if @activities.any? && !@unit.is_example
      @description = "Vote now for your favorite #{@unit.name} activities that you'd like to see happen. There are currently #{@unit.activities.count} activities. The Unit will consider the vote tally in determining which activites they schedule."
    else
      @description = "Engaging Scout unit outdoor, fundraising and covid safe and other types of activities submitted and voted on by users."
    end
    @title = 'Activity Vote - Scout Activity'
    @title = "#{@unit.name} - #{@title}" unless @unit.is_example?
    return unless signed_in? && current_user.unit.nil?
    flash[:alert] = "To vote, select a Unit in your <a href='/users/#{current_user.id}/edit'>Profile</a> settings."
  end

  def show
    unit = @activity.unit
    @is_example = true if unit.is_example
    @votes = @activity.unit_votes.includes(:user).group(:user_id).count
    @title = activity_page_title(@activity)
    unit.increment!(:visit_event_count)
    @questions = @activity.questions
    @description = if @is_example
                     "#{@activity.name} is an idea for a Troop activity. "
                   else
                     @activity.name + " is a proposed activity by #{unit.name}."
                   end
    @description += @activity.summary_new || ''
    @description += "Will include the following: #{@activity.types.join(', ')}" if @activity.types.any?
    @description += " This activity also has been tagged with the following categories: #{@activity.categories.join(', ')}." if @activity.categories.any?
  end

  def archive_activity
    @activity = @unit.activities.find(params[:activity_id])
    @activity.toggle!(:is_archived)
    message = if @activity.is_archived
                'Activity is archived, and no longer in the activity voting list.'
              else
                'Activity is unarchived and showing in the activity voting list.'
              end
    redirect_to unit_activity_path(@unit, @activity), notice: message
  end

  def copy
    activity = Activity.find(params[:activity_id])
    new_activity = Activity.duplicate(activity)
    new_activity.author_id = current_user.id
    new_activity.unit = current_user.unit
    if new_activity.save
      activity.increment!(:copy_count)
      activity.images.each do |image|
        new_activity.images.attach image.blob
      end
      redirect_back(fallback_location: unit_activities_path(current_user.unit), notice: "'#{new_activity.name}' copied to your Unit.")
    else
      begin
        Bugsnag.notify(new_activity)
      rescue StandardError
        nil
      end
      redirect_to unit_activities_path(current_user.unit), alert: "There was a problem. The activity '#{new_activity.name}' was not copied to your Unit."
    end
  end

  def new
    @activity = Activity.new
    @title = "#{@unit.name} - New Activity - Scout Activity"
    @description = "Propose and activity for #{@unit.name} that Scouts can vote on as an activity to do."
  end

  def edit
    @title = activity_page_title(@activity)
  end

  def create
    @activity = @unit.activities.new(activity_params)
    @activity.author = current_user

    if @activity.save
      redirect_to unit_activities_path(@unit), notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  def update
    if @activity.update(activity_params)
      redirect_to unit_activity_path(@unit, @activity), notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to unit_activities_url(@unit), notice: 'Activity was successfully destroyed.'
  end

  def ideas_for_troop_activities
    @unit = Unit.example.first
    @activities = Unit.example.first.activities.votable.order(unit_votes_count: :desc)
    @title = "Troop activity ideas - Scout Activity"
    @no_vote = false
    @description = "A list of #{Unit.example.first.activities.count} Scouting activities that could be used by your Unit, ranging from outdoor, merit badge-oriented, fundraising, covid safe and other types of activities submitted and voted on by users."
    @activities = @activities.where(params[:filter]) if params[:filter]
    render :index
  end

  def ideas_for_fundraising_activities
    @unit = Unit.example.first
    @activities = Unit.example.first.activities.fundraising.votable
    @title = "Unit fundraising activity ideas - Scout Activity"
    @no_vote = false
    @description = "A list of #{Unit.example.first.activities.fundraising.count} Scouting fundraising activities that could help your Unit raise funds, submitted and voted on by users."
    @activities = @activities.where(params[:filter]) if params[:filter]
    render :index
  end

  def ideas_for_covid_safe_troop_activities
    @unit = Unit.example.first
    @activities = Unit.example.first.activities.votable.covid_safe
    @title = "COVID safe ideas for Troop activities - Scout Activity"
    @no_vote = false
    @description = "A list of #{Unit.example.first.activities.covid_safe.count} Scouting activities that may be more COVID safe, submitted and voted on by users."
    @activities = @activities.where(params[:filter]) if params[:filter]
    render :index
  end

  private

  def require_unit_user
    redirect_to root_path unless signed_in? && current_user.unit == @unit || current_user.admin?
  end

  def require_author_admin_owner
    redirect_to root_path unless signed_in? && (@activity.author == current_user || current_user.admin_or_owner?)
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def set_title
    @title = if @unit
               "#{@unit.name} - Activities - Scout Activity"
             else
               "Activities - Scout Activity"
             end
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(
      :name, :author, :summary, :itinerary, :description, :duration_days,
      :is_high_adventure, :is_author_volunteering, :is_hiking, :is_camping,
      :is_plane, :is_virtual, :is_swimming, :is_community_service, :is_archived,
      :is_biking, :is_cooking, :is_boating, :is_covid_safe, :is_game, :is_fundraising,
      :is_merit_badge, :is_international, :summary_new, :is_troop, :is_pack, images: []
      )
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def activity_page_title(activity)
    result = "#{activity.name} - Scout Activity"
    result = "#{activity.unit.name} - #{result}" unless activity.unit.is_example?
    result
  end
end

app/views/activities/_actions.html.haml
- if signed_in? && (( @activity.author == current_user && current_user.unit == @activity.unit) || current_user.admin_or_owner?)
  #actions
    - if @activity.author == current_user || (current_user.admin_or_owner? && current_user.unit == @activity.unit) || (current_user.admin? && @activity.unit.example?)
      = link_to edit_unit_activity_path(@activity.unit, @activity), class: 'action action-link', id: 'activity-edit-link' do
        = fa_icon "edit"
      - if @activity.is_archived?
        = button_to "Unarchive", unit_activity_archive_activity_path(@activity.unit, @activity), class: 'btn btn-primary action', id: 'unarchive-button'
      - else
        = button_to "Archive", unit_activity_archive_activity_path(@activity.unit, @activity), class: 'btn btn-primary action', id: 'archive-button'
      = button_to "Destroy", unit_activity_path(@activity.unit, @activity), method: :delete, data: { confirm: 'Are you sure? This will destroy the Activity and return any votes placed for it.'}, class: 'btn btn-danger action', id: 'destroy-button'
    - if current_user&.admin_or_owner?
      = link_to unit_activity_copy_path(current_user.unit, @activity), id: 'copy-activity-link', class: 'action action-link', method: :post do
        = fa_icon "copy"

app/views/activities/_activities_filter.haml
.row
  .col-md-1
  .col-md-10
    %nav.nav#activity-filter.justify-content-center
      = link_to troop_activity_ideas_path(filter: 'is_covid_safe'), class: "nav-link #{params[:filter]=='is_covid_safe' ? 'active':nil}", id: 'covid-safe-filter' do
        = fa_icon "head-side-mask"
      = link_to troop_activity_ideas_path(filter: 'is_hiking'), class: "nav-link #{params[:filter]=='is_hiking' ? 'active':nil}", id: 'hiking-filter' do
        = fa_icon "hiking"
      = link_to troop_activity_ideas_path(filter: 'is_swimming'), class: "nav-link #{params[:filter]=='is_swimming' ? 'active':nil}", id: 'swimming-filter' do
        = fa_icon "swimmer"
      = link_to troop_activity_ideas_path(filter: 'is_biking'), class: "nav-link #{params[:filter]=='is_biking' ? 'active':nil}", id: 'biking-filter' do
        = fa_icon "biking"
      = link_to troop_activity_ideas_path(filter: 'is_plane'), class: "nav-link #{params[:filter]=='is_plane' ? 'active':nil}", id: 'flying-filter' do
        = fa_icon "plane"
      = link_to troop_activity_ideas_path(filter: 'is_cooking'), class: "nav-link #{params[:filter]=='is_cooking' ? 'active':nil}", id: 'cooking-filter' do
        = fa_icon "utensils"
      = link_to troop_activity_ideas_path(filter: 'is_merit_badge'), class: "nav-link #{params[:filter]=='is_merit_badge' ? 'active':nil}", id: 'merit-badge-filter' do
        = image_tag "merit-badge.svg", width: '26px'
      = link_to troop_activity_ideas_path(filter: 'is_camping'), class: "nav-link #{params[:filter]=='is_camping' ? 'active':nil}", id: 'camping-filter' do
        = fa_icon "campground"
      = link_to troop_activity_ideas_path(filter: 'is_virtual'), class: "nav-link #{params[:filter]=='is_virtual' ? 'active':nil}", id: 'virtual-filter' do
        = fa_icon "video"
      = link_to troop_activity_ideas_path(filter: 'is_fundraising'), class: "nav-link #{params[:filter]=='is_fundraising' ? 'active':nil}", id: 'fundraising-filter' do
        = fa_icon "dollar-sign"
      = link_to troop_activity_ideas_path(filter: 'is_game'), class: "nav-link #{params[:filter]=='is_game' ? 'active':nil}", id: 'game-filter' do
        = fa_icon "trophy"
      = link_to troop_activity_ideas_path(filter: 'is_boating'), class: "nav-link #{params[:filter]=='is_boating' ? 'active':nil}", id: 'boating-filter' do
        = fa_icon "anchor"
      = link_to troop_activity_ideas_path(filter: 'is_community_service'), class: "nav-link #{params[:filter]=='is_community_service' ? 'active':nil}", id: 'community-service-filter' do
        = fa_icon "store"
      = link_to troop_activity_ideas_path(filter: 'is_international'), class: "nav-link #{params[:filter]=='is_international' ? 'active':nil}", id: 'international-filter' do
        = image_tag "world-crest.png", width: '26px'
      = link_to troop_activity_ideas_path(filter: 'is_high_adventure'), class: "nav-link #{params[:filter]=='is_high_adventure' ? 'active':nil}", id: 'high-adventure-filter' do
        = fa_icon "mountain"
      = link_to "clear", troop_activity_ideas_path, class: 'nav-link', id: 'clear-filter'

app/views/activities/_activity.html.haml
%article
  .row
    .col-md-8
      - images = activity.images
      - if images.any?
        .image
          - if images.first.variable?
            = image_tag activity.images.first.variant(resize_to_limit: [100, 100]), class: 'img-fluid rounded'
          / - if images.count > 1 && images[1].variable?
          /   = image_tag images[1].variant(resize_to_limit: [100, 100]), class: 'img-fluid rounded'

      %h1.name
        - if activity.unit.is_example && action_name != 'index'
          = link_to activity.name, activity_path(activity)
        - else
          = link_to activity.name, unit_activity_path(activity.unit, activity)
        &nbsp;
      - if activity.created_at > Time.now - 7.days
        .badge.badge-primary.new-badge NEW
      = render partial: 'activity_icons', locals: { activity: activity }
      - if activity.activity_icons?
        \|
      %span.text-muted
        = pluralize(activity.duration_days, 'day')
      - if signed_in? && current_user.admin_or_owner?
        .copy
          = link_to unit_activity_copy_path(activity.unit, activity), id: "copy-activity-#{activity.id}-link", method: :post do
            = fa_icon "copy"

    - if @no_vote != true
      .col-md-4
        .voting
          .votes-count(id="activity-#{activity.id}-total-count")
            - unless activity.is_archived?
              = activity.unit_votes_count || 0
              / .votes
              / # = "vote".pluralize(activity.unit_votes_count)
          - if signed_in? && current_user.unit == activity.unit || activity.unit.example?
            .vote
              - unless activity.is_archived?
                - if signed_in?
                  - if current_user.unit == activity.unit
                    - if current_user.unit_votes_available.positive?
                      = button_to unit_unit_votes_path(activity.unit, activity_id: activity.id), class: 'btn btn-success', id: "place-vote-#{activity.id}" do
                        = fa_icon "thumbs-up"
                    - if current_user.unit_votes.where(unit_id: current_user.unit_id).find_by(activity_id: activity.id)
                      - vote = current_user.where(unit_id: current_user.unit_id).unit_votes.order(created_at: :desc).where(activity_id: activity.id).first
                      = button_to unit_unit_vote_path(activity.unit, vote), method: :delete, class: 'btn btn-danger', id: "remove-vote-#{activity.id}" do
                        = fa_icon "minus"
                  - elsif activity.unit.example?
                    - if current_user.example_votes_available.positive?
                      = button_to unit_unit_votes_path(activity.unit, activity_id: activity.id), class: 'btn btn-success', id: "place-vote-#{activity.id}" do
                        = fa_icon "thumbs-up"
                    - if current_user.unit_votes.where(unit_id: Unit.example.first.id).find_by(activity_id: activity.id)
                      - vote = current_user.unit_votes.where(unit_id: Unit.example.first.id).order(created_at: :desc).where(activity_id: activity.id).first
                      = button_to unit_unit_vote_path(activity.unit, vote), method: :delete, class: 'btn btn-danger', id: "remove-vote-#{activity.id}" do
                        = fa_icon "minus"
            .votes-count
              - unless activity.is_archived?
                - count = activity.unit_votes.where(user: current_user).count
                = count || 0

    / - if @no_vote == true && activity.images.attached?

app/views/activities/_discussion.html.haml
#discussion
  .row
    .col-md-12
      %h2 Discussion
      = render partial: 'questions/question', collection: @questions

      - if signed_in? && @unit == current_user.unit
        = link_to "Question, comment?", new_unit_activity_question_path(@unit, @activity), class: 'question-link', id: 'question-link'

  - unless signed_in?
    .row
      .col-md-12
        = link_to "Sign in to ask questions/comments", sign_in_path, class: 'sign-in-link'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

app/views/activities/ideas_for_covid_safe_troop_activities.html.haml
%main
  .row
    .col-md-12
      %h1
        COVID Safe Troop Activity Ideas

  - if signed_in?
    .row
      .col-md-3
      .col-md-6
        .text-center.mb-5
          .vote-count
            .badge.badge-primary#votes-available= current_user.unit_votes_available
            %span.text-muted votes left

  #activities

    .row
      .col-md-1
      .col-md-10
        .important-icon= fa_icon "head-side-mask"


    .row
      .col-md-1
      .col-md-10
        = render @activities

app/views/activities/ideas_for_fundraising_activities.html.haml
%main
  .row
    .col-md-12
      %h1
        Fundraising Activity Ideas

  - if signed_in?
    .row
      .col-md-3
      .col-md-6
        .text-center.mb-5
          .vote-count
            .badge.badge-primary#votes-available= current_user.unit_votes_available
            %span.text-muted votes left

  #activities

    .row
      .col-md-1
      .col-md-10
        .important-icon= fa_icon "dollar-sign"


    .row
      .col-md-1
      .col-md-10
        = render @activities

app/views/activities/ideas_for_troop_activities.html.haml
%main
  .row
    .col-md-12
      %h1
        = Unit.example.first.activities.count
        Troop Activity Ideas

  - if signed_in?
    .row
      .col-md-3
      .col-md-6
        .text-center.mb-5
          .vote-count
            .badge.badge-primary#votes-available= current_user.example_votes_available
            %span.text-muted votes left

  = render 'activities_filter'
  .row
    .col-md-1
    .col-md-10
      #activities
        = render @activities

app/views/activities/ideas_for_troop_fundraising_activities.html.haml
%main
  .row
    .col-md-12
      %h1
        = @activities_count
        Troop Fundraising Activity Ideas

  #activities

    .row
      .col-md-1
      .col-md-10
        .important-icon= fa_icon "head-side-mask"


    .row
      .col-md-1
      .col-md-10
        = render @activities

app/views/activities/index.html.haml
#activities

  %h1
    - if action_name == 'ideas_for_covid_safe_troop_activities'
      = Unit.example.first.activities.votable.covid_safe.count
      COVID Safe Activity Ideas
    - elsif action_name == 'ideas_for_fundraising_activities'
      = Unit.example.first.activities.votable.covid_safe.count
      Fundraising Activity Ideas
    - elsif @unit.is_example
      = Unit.example.first.activities.count
      Unit Activity Ideas
    - else
      = @unit.name
      Activity Vote

  - if (signed_in? && @unit == current_user.unit) || (signed_in? && @unit.example?)
    .row
      .col-md-3
      .col-md-6
        .text-center.mb-5
          .vote-count
            .badge.badge-primary#votes-available
              - if @unit.example?
                = current_user.example_votes_available
              - else
                = current_user.unit_votes_available
            %span.text-muted votes left

  - if @activities.any?

    - unless signed_in?
      .text-center.mb-4= button_to "Sign in or sign up to vote", sign_in_path, method: :get, class: 'btn btn-primary'


    = render 'activities_filter'

    .row
      .col-md-1
      .col-md-10
        %ul.activities.list-group
          = render(@activities)

  - if @high_adventure_activities&.any?
    .row
      .col-md-1
      .col-md-10
        %h2 High Adventure
        %p.text-muted.text-center.mb-4 Please only vote if you are at least 13 years old

        %ul.activities.list-group
          = render partial: 'activity', collection: @high_adventure_activities, as: :activity

  - if @activities.empty? && @high_adventure_activities.empty?
    %p.text-center
      No activities have been proposed.
      - if signed_in? && current_user.unit == @unit
        = link_to "Propose an Activity.", new_unit_activity_path(@unit)
      - elsif !signed_in?
        = link_to "Sign in", sign_in_path
        or 
        = link_to "sign up", sign_up_path
        to vote or propose and activity.
      
    = render 'share_link'

  - if @archived_activities&.any?
    .row
      .col-md-1
      .col-md-10
        %h2 Archived

        %ul.activities.list-group
          = render partial: 'activity', collection: @archived_activities, as: :activity

  .row
    .col-md-12.text-center
      .share-link
        = link_to 'http://www.facebook.com/sharer.php?u=' +request.url, target: :blank do
          = fa_icon "share"
          Share

app/views/activities/new.html.haml
%h1 What's your Activity idea?


= image_tag "feature-activity-icons.png", class: 'img-fluid rounded shadow-sm p-0 mb-5'

- if signed_in?
  = render 'form'

- else
  .mt-4= button_to "Sign in to propose an activity", sign_in_path, method: :get, class: 'btn btn-primary'

app/views/activities/show.html.haml
.container
  - if @is_example
    = render partial: 'breadcrumbs', locals: { link_url: troop_activity_ideas_path, link_text: 'Ideas for Troop activities' }
  - elsif @unit
    = render partial: 'breadcrumbs', locals: { link_url: unit_activities_path(@unit), link_text: 'All activities' }

%main#activity
  %article
    .container
      .row
        .col-md-9

          - if @activity.created_at > Time.now - 7.days
            %span.badge.badge-primary.new-badge NEW
          %h1
            - unless @is_example
              = @activity.unit.name
              \-
            = @activity.name
          .activity-icons= render partial: 'activity_icons', locals: { activity: @activity }
          = pluralize(@activity.duration_days, "day")
        - unless @is_example
          .col-md-3
            #activity-vote-count
              .activity-count
                = @activity.unit_votes_count || 0
              .votes= "vote".pluralize(@activity.unit_votes_count)

      .row
        .col-md-9

          %h2 Summary
          %p= @activity.summary_new

          %br

          - if @activity.description.present?
            %h2 Description
            = @activity.description

          - if @activity.itinerary.present?
            %h2 Itinerary
            = @activity.itinerary

    - if @activity.images.attached?
      .container-fluid.pl-0.pr-0
        #activity-images
          - @activity.images.each do |image|
            - next unless image.variable?
            .text-center= image_tag image.variant(resize_to_limit: [800, 800]), class: 'activity-image img-fluid rounded'

    .container
      - unless @is_example
        .row
          .col-md-7

            = render 'discussion'

      - if @activity.author && !@is_example
        .row
          .col-md-7
            %h2 Details
            #proposer
              .row
                .col-md-9
                  %strong Proposed by:
                  %br
                  = @activity.author.name_email
                  - if @activity.is_author_volunteering?
                    %br
                      The proposer is willing to help lead this activity.

      .row
        .col-md-7
          = render 'actions'